### ISSUE TITLE
Experiments for ESIP Presentation

### ISSUE THREAD

**Issue by rajadain** [azavea/noaa-hydro-data#45]
ESIP has a meeting in July 19-22 https://www.esipfed.org/meetings 

Prepare a demo of our work for this meeting.

**Comment by lewfish** [comment]
A high-level plan for getting something presentable at ESIP. We should aim to get this all working locally first on a tiny subset of the dataset if possible. 

- Pick a query that Fernando suggested, and make a concrete instantiation of it. To start, we should pick a time range that either uses the reanalysis OR the prediction dataset. 
- Time the query using the naive approach, ie. download NetCDF files and do the calculation. This will be slow because we are downloading huge amounts of irrelevant data.
- Time the query using the Zarr-encoded data that is on S3 .
- Rechunk the data and save it on S3. Not sure, but I think doing it for the whole dataset is going to require a huge amount of resources. We should probably doing it for a large, but manageable subset of the dataset. It needs to be large enough to make the benchmarks "realistic."
- Re-encode the data using Parquet for point-based datasets (ie. the ones representing stream reaches). Try different ways of chunking it.
- Time the query using the Parquet-encoded data.
- Repeat the queries using different numbers of cores of computation to test scalability.
- Repeat the queries using (interesting) variations on the query or another query that Fernando suggested.
- Display the timings for the different approaches in a table or graph

**Comment by lewfish** [comment]
Hey @vlulla I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/noaa-flood-mapping-5efb7080a371890016f405f7/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by lewfish** [comment]
Note that we should keep experiments small at first and use them to estimate how much the full set of experiments will cost and pass that on Stephanie.
